### ISSUE TITLE
4-music-player-ytdl not playing song

### ISSUE THREAD

**Issue by bycop** [discordx-ts/templates#77]
Hello,
I've used npx create-discordx to init a project with 4-music-player-ytdl
I did not modify any of the files
When I run the command /music play <url>
The bot join my channel, send the control embed, start playing the song with the time on the embed 
![image](https://user-images.githubusercontent.com/44951701/188274398-fbc98ef1-c009-4132-b333-d8d9f2a36d7a.png)

But no song is playing on the voice channel, no green circle or anything.
I've tried to setVolume(100) but it's the same result.

Hope someone can help
(I don't attach code since it's the same as "4-music-player-ytdl")

**Comment by TeamWolfyta** [comment]
Will have a look into this in a sec, Currently trying to fix something on my pc.

**Comment by TeamWolfyta** [comment]
I'm getting green circle and that's it. No sound either

**Comment by bycop** [comment]
> I'm getting green circle and that's it. No sound either

With the default installation ? 
Do I need a driver or anything on my pc ?

**Comment by TeamWolfyta** [comment]
Not sure, I can't really make heads of tails of this, trying to look into it tho

**Comment by TeamWolfyta** [comment]
I can't seem to figure it out, I've had these sorts of issues with ytdl based music players in the past and they have just brought nothing but trouble, if at all possible try lavalink... @oceanroleplay might be able to figure this out better as he coded it but I don't see much wrong with it.

**Comment by oceanroleplay** [comment]
> Hello, I've used npx create-discordx to init a project with 4-music-player-ytdl I did not modify any of the files When I run the command /music play The bot join my channel, send the control embed, start playing the song with the time on the embed ![image](https://user-images.githubusercontent.com/44951701/188274398-fbc98ef1-c009-4132-b333-d8d9f2a36d7a.png)
> 
> But no song is playing on the voice channel, no green circle or anything. I've tried to setVolume(100) but it's the same result.
> 
> Hope someone can help (I don't attach code since it's the same as "4-music-player-ytdl")

provide the song link also, I will test it

**Comment by bycop** [comment]
> > Hello, I've used npx create-discordx to init a project with 4-music-player-ytdl I did not modify any of the files When I run the command /music play The bot join my channel, send the control embed, start playing the song with the time on the embed ![image](https://user-images.githubusercontent.com/44951701/188274398-fbc98ef1-c009-4132-b333-d8d9f2a36d7a.png)
> > But no song is playing on the voice channel, no green circle or anything. I've tried to setVolume(100) but it's the same result.
> > Hope someone can help (I don't attach code since it's the same as "4-music-player-ytdl")
> 
> provide the song link also, I will test it

By example: https://www.youtube.com/watch?v=yagjiCZRtLY

**Comment by oceanroleplay** [comment]
unable to reproduce any issue, example is working just fine

**Comment by bycop** [comment]
Do you have a driver, codecs or anything ?

**Comment by oceanroleplay** [comment]
no, if you want I can run the demo in container
